package JFramesMOC;

import BD.UsuarioBD;
import javax.swing.JOptionPane;
import Classes.Usuario;

public class CUsuario extends javax.swing.JFrame {

    Usuario usu;
    UsuarioBD bd = new UsuarioBD();
    TLogin tela_t;
    public CUsuario() {
        initComponents();
    }

    public CUsuario(Usuario usu) {
        initComponents();
        this.usu=usu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        txtNome = new javax.swing.JTextField();
        CB_Praca = new javax.swing.JCheckBox();
        CB_Metro = new javax.swing.JCheckBox();
        CB_Cinema = new javax.swing.JCheckBox();
        CB_Shopping = new javax.swing.JCheckBox();
        RB_Nao = new javax.swing.JRadioButton();
        RB_Sim = new javax.swing.JRadioButton();
        txtFormacao = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Preferências pessoais:");
        jLayeredPane2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));
        jLayeredPane2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail");
        jLayeredPane2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jLayeredPane2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 300, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RG");
        jLayeredPane2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cadastro de Usuário");
        jLayeredPane2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));
        jLayeredPane2.add(txtRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuário");
        jLayeredPane2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        jLayeredPane2.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        jLayeredPane2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Formação");
        jLayeredPane2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 100, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 100, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Pesquisar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 100, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Já estou cadastrado");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 190, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Sair");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 100, 30));
        jLayeredPane2.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 300, 20));
        jLayeredPane2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 300, -1));

        buttonGroup1.add(CB_Praca);
        CB_Praca.setForeground(new java.awt.Color(255, 255, 255));
        CB_Praca.setSelected(true);
        CB_Praca.setText("Praça");
        CB_Praca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_PracaActionPerformed(evt);
            }
        });
        jLayeredPane2.add(CB_Praca, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        buttonGroup1.add(CB_Metro);
        CB_Metro.setForeground(new java.awt.Color(240, 240, 240));
        CB_Metro.setText("Metro");
        jLayeredPane2.add(CB_Metro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        buttonGroup1.add(CB_Cinema);
        CB_Cinema.setForeground(new java.awt.Color(240, 240, 240));
        CB_Cinema.setText("Cinema");
        jLayeredPane2.add(CB_Cinema, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        buttonGroup1.add(CB_Shopping);
        CB_Shopping.setForeground(new java.awt.Color(240, 240, 240));
        CB_Shopping.setText("Shopping");
        jLayeredPane2.add(CB_Shopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        buttonGroup2.add(RB_Nao);
        RB_Nao.setForeground(new java.awt.Color(240, 240, 240));
        RB_Nao.setText("Não");
        jLayeredPane2.add(RB_Nao, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        buttonGroup2.add(RB_Sim);
        RB_Sim.setForeground(new java.awt.Color(240, 240, 240));
        RB_Sim.setSelected(true);
        RB_Sim.setText("Sim");
        jLayeredPane2.add(RB_Sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        txtFormacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serviços gerais", "Saúde", "Funcionario público", "Exatas", "Biológicas", "Humanas", "Informática", " " }));
        txtFormacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormacaoActionPerformed(evt);
            }
        });
        jLayeredPane2.add(txtFormacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 300, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Movimentação perto da residência:");
        jLayeredPane2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Locais de proximidade:");
        jLayeredPane2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 170, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nome");
        jLayeredPane2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Senha");
        jLayeredPane2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vintage-grunge-aesthetics-australia.jpg"))); // NOI18N
        jLayeredPane2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(810, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(rootPane,
                bd.excluirUsuario(
                        Integer.parseInt(txtId.getText())));

        limparCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        usu.setNome_usu(txtNome.getText());
        usu.setLogin(txtLogin.getText());
        usu.setRG(txtRG.getText());
        usu.setFormacao_usu(txtFormacao.getSelectedItem().toString());
        usu.setEmail_usu(txtEmail.getText());
        usu.setSenha(txtSenha.getText());

        JOptionPane.showMessageDialog(rootPane,
                bd.alterarUsuario(usu));

        limparCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        usu = bd.pesquisarUsuarioPorID(
                Integer.parseInt(txtId.getText()));

        if (usu == null) {
            JOptionPane.showMessageDialog(rootPane,
                    "Usuario não encontrado!");

        } else {
            txtNome.setText(usu.getNome_usu());
            txtLogin.setText(usu.getLogin());
            txtRG.setText(usu.getRG());
            txtFormacao.setSelectedItem(usu.getFormacao_usu());
            txtEmail.setText(usu.getEmail_usu());
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        usu = new Usuario();
        usu.setNome_usu(txtNome.getText());
        usu.setLogin(txtLogin.getText());
        usu.setRG(txtRG.getText());
        usu.setFormacao_usu(txtFormacao.getSelectedItem().toString());
        usu.setEmail_usu(txtEmail.getText());
        usu.setSenha(txtSenha.getText());

        if (CB_Shopping.isSelected()) {
            usu.setPref_geo_usu("Shopping");
        } else if (CB_Cinema.isSelected()) {
            usu.setPref_geo_usu("Cinema");
        } else if (CB_Metro.isSelected()) {
            usu.setPref_geo_usu("Metro");
        } else if (CB_Praca.isSelected()) {
            usu.setPref_geo_usu("Praça");
        }

        if (RB_Sim.isSelected()) {
            usu.setMovimentacao_usu(true);
        } else if (RB_Nao.isSelected()) {
            usu.setMovimentacao_usu(false);
        }

        JOptionPane.showMessageDialog(rootPane, bd.inserir(usu));

        limparCampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CB_PracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_PracaActionPerformed

    }//GEN-LAST:event_CB_PracaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     tela_t=new TLogin();
     tela_t.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtFormacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormacaoActionPerformed

    public void limparCampos() {
        txtNome.setText("");
        txtId.setText("");
        txtLogin.setText("");
        txtRG.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CB_Cinema;
    private javax.swing.JCheckBox CB_Metro;
    private javax.swing.JCheckBox CB_Praca;
    private javax.swing.JCheckBox CB_Shopping;
    private javax.swing.JRadioButton RB_Nao;
    private javax.swing.JRadioButton RB_Sim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtFormacao;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRG;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
